# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Weatherbot Backend on Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Prepare Setup
      run: sudo apt install -y libapr1-dev libcurl4-openssl-dev libjson-c-dev cmake binutils make rustc pkg-config
        
    - name: Clone Required Libraries
      run: git clone https://github.com/smartnode/telebot.git
           git clone https://github.com/AhmedNGaber/weatherbot-rust-c-wrapper.git
      
    - name: Build 
      # Build Rust library
      run: cd ${{github.workspace}}/weatherbot-rust-c-wrapper && cargo build
           cd ${{github.workspace}}/build
           cmake .. && make telebot && make

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

